# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProjetoAutismo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod 'Firebase'
	pod 'Firebase/Database'
	pod 'MessageKit'
  	pod 'Firebase/Core'
  	pod 'Firebase/Auth'
  	pod 'Firebase/Database'
  	pod 'Firebase/Storage'
  	pod 'Firebase/Firestore'
    	post_install do |installer|
    	  installer.pods_project.targets.each do |target|
      	    if target.name == 'MessageKit'
               target.build_configurations.each do |config|
          	  config.build_settings['SWIFT_VERSION'] = '4.2'
               end
      	    end
    	  end
  	end	


  # Pods for ProjetoAutismo

  # add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

end
